---
title: "You Report Title (concise and descriptive)"
author: "Your Name"
date: "West Chester University"
output: 
  html_document: 
    toc: yes
    toc_depth: 4
    toc_float: yes
    code_folding: hide
    code_download: yes
    smooth_scroll: yes
    number_sections: yes
    theme: readable
---
      
<style type="text/css">
div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0;
}
h1.title {
  font-size: 24px;
  color: DarkRed;
  text-align: center;
}
h4.author { 
  /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  text-align: center;
}
h4.date { 
  /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
  text-align: center;
}
h1 { 
    /* Header 3 - and the author and data headers use this too  */
    font-size: 22px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: center;
}
h2 { 
    /* Header 3 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}
h3 { 
    /* Header 3 - and the author and data headers use this too  */
    font-size: 15px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    font-face: bold;
    text-align: left;
}
h4 { 
    /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}
   /* center maps using chunk option: fig.align='center' */
.html-widget {
    margin: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,       
                      warning = FALSE,   
                      result = TRUE,   
                      message = FALSE,
                      comment = NA)
```


# Obtaining Data for Analysis

The National Health and Nutrition Survey data as subsetted for use in Hosmer and Lemeshow’s (2000) Applied Logistic Regression: Second edition was obtained for use in this analysis.  This data has been compiled by the Centers for Disease Control (CDC) with the intent to assess the health and nutritional status of both adults and children in the United States. Additional information regarding the NHANES can be found at <a href="https://www.cdc.gov/nchs/nhanes/about_nhanes.htm">https://www.cdc.gov/nchs/nhanes/about_nhanes.htm</a>

